### ISSUE TITLE
[BUG] Broken link

### ISSUE THREAD

**Issue by Pradumnasaraf** [KashishLakhara04/KashishLakhara04#1]
### Issue description
There is a broken link in the README

### Screenshot
![Screenshot from 2022-08-08 11-36-41](https://user-images.githubusercontent.com/51878265/183350516-55ff8749-06d5-4f40-8263-61b190912b9a.png)

**Comment by KashishLakhara04** [comment]
Thanks for highlighting the issue. Now it's fixed 😊

**Comment by Pradumnasaraf** [comment]
Awesome, closing this Issue!
